add option to force mavlink_passthrough
Auterion/agent_protocol_splitter pull request #18
Opened 2022-02-09 22:50 UTC by DanielePettenuzzo

I ran out of time so I will test this first thing in the morning.

2022-02-09 22:55 UTC, TSC21 requested changes

2022-02-09 22:55 UTC, TSC21 commented on src/protocol_splitter.cpp
> +		case 'm': _options.force_mavlink_passthrough = true; 		break;
Can you fix the identations?

2022-02-09 22:55 UTC, TSC21 commented on src/protocol_splitter.cpp
> +static void parse_env_variables()
Why do we need this if we can just pass the argument when starting the app then?

2022-02-09 23:00 UTC, DanielePettenuzzo commented on src/protocol_splitter.cpp
> +		case 'm': _options.force_mavlink_passthrough = true; 		break;
Strange. I didn't notice it. Thank you

2022-02-09 23:03 UTC, TSC21 commented on src/protocol_splitter.cpp
> +static void parse_env_variables()
Well this is a workaround anyway for now. Question is: can we take a more generic env variable name? This a public repo and others will use it so makes more sense to set a second env variable to make it cleaner or have this as a separate branch (not merged to master).

I will anyway create the PR tomorrow morning to make the check more robust (didn't have the time tonight).

2022-02-10 09:39 UTC, TSC21 approved these changes

2022-02-10 09:39 UTC, merged